//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! opencode
//! Source: openapi.json
//! Version: 1.0.0
//! Generated by `oas3-gen v0.25.3`
//!
//! opencode api

use std::time::Duration;
use super::types::*;
use anyhow::Context;
use reqwest::{Client, Url};
use validator::Validate;
pub const BASE_URL: &str = "https://example.com/";
#[derive(Debug, Clone)]
pub struct OpencodeClient {
    pub client: Client,
    pub base_url: Url,
}
impl Default for OpencodeClient {
    fn default() -> Self {
        Self::new()
    }
}
impl OpencodeClient {
    /// Create a client using the OpenAPI `servers[0]` URL.
    #[must_use]
    #[track_caller]
    pub fn new() -> Self {
        let client = reqwest::Client::builder()
            .tcp_keepalive(Duration::from_secs(15))
            .pool_idle_timeout(None)
            .build()
            .expect("failed to build HTTP client");

        Self {
            client,
            base_url: Url::parse(BASE_URL).expect("valid base url"),
        }
    }
    /// Create a client with a custom base URL.
    pub fn with_base_url(base_url: impl AsRef<str>) -> anyhow::Result<Self> {
        let client = reqwest::Client::builder()
            .tcp_keepalive(Duration::from_secs(15))
            .pool_idle_timeout(None)
            .build()
            .context("failed to build HTTP client")?;
        Ok(Self {
            client,
            base_url: Url::parse(base_url.as_ref()).context("parsing base url")?,
        })
    }
    /// Create a client from an existing `reqwest::Client`.
    pub fn with_client(base_url: impl AsRef<str>, client: Client) -> anyhow::Result<Self> {
        let url = Url::parse(base_url.as_ref()).context("parsing base url")?;
        Ok(Self { client, base_url: url })
    }
    /// List agents
    ///
    /// Get a list of all available AI agents in the OpenCode system.
    ///
    /// * Path: `GET /agent`
    pub async fn app_agents(&self, request: AppAgentsRequest) -> anyhow::Result<AppAgentsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("agent");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(AppAgentsRequest::parse_response(response).await?)
    }
    /// Set auth credentials
    ///
    /// Set authentication credentials
    ///
    /// * Path: `PUT /auth/{providerID}`
    pub async fn auth_set(&self, request: AuthSetRequest) -> anyhow::Result<AppLogResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("auth")
            .push(&request.path.provider_id.to_string());
        let mut req_builder = self.client.put(url);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(AuthSetRequest::parse_response(response).await?)
    }
    /// Remove auth credentials
    ///
    /// Remove authentication credentials
    ///
    /// * Path: `DELETE /auth/{providerID}`
    pub async fn auth_remove(&self, request: AuthRemoveRequest) -> anyhow::Result<AppLogResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("auth")
            .push(&request.path.provider_id.to_string());
        let response = self.client.delete(url).send().await?;
        Ok(AuthRemoveRequest::parse_response(response).await?)
    }
    /// List commands
    ///
    /// Get a list of all available commands in the OpenCode system.
    ///
    /// * Path: `GET /command`
    pub async fn command_list(&self, request: CommandListRequest) -> anyhow::Result<CommandListResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("command");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(CommandListRequest::parse_response(response).await?)
    }
    /// Get configuration
    ///
    /// Retrieve the current OpenCode configuration settings and preferences.
    ///
    /// * Path: `GET /config`
    pub async fn config_get(&self, request: ConfigGetRequest) -> anyhow::Result<ConfigGetResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("config");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ConfigGetRequest::parse_response(response).await?)
    }
    /// Update configuration
    ///
    /// Update OpenCode configuration settings and preferences.
    ///
    /// * Path: `PATCH /config`
    pub async fn config_update(&self, request: ConfigUpdateRequest) -> anyhow::Result<ConfigUpdateResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("config");
        let mut req_builder = self.client.patch(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(ConfigUpdateRequest::parse_response(response).await?)
    }
    /// List config providers
    ///
    /// Get a list of all configured AI providers and their default models.
    ///
    /// * Path: `GET /config/providers`
    pub async fn config_providers(&self, request: ConfigProvidersRequest) -> anyhow::Result<ConfigProvidersResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("config")
            .push("providers");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ConfigProvidersRequest::parse_response(response).await?)
    }
    /// Subscribe to events
    ///
    /// Get events
    ///
    /// * Path: `GET /event`
    pub async fn event_subscribe(&self, request: EventSubscribeRequest) -> anyhow::Result<EventSubscribeResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("event");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(EventSubscribeRequest::parse_response(response).await?)
    }
    /// Get MCP resources
    ///
    /// Get all available MCP resources from connected servers. Optionally filter by name.
    ///
    /// * Path: `GET /experimental/resource`
    pub async fn experimental_resource_list(
        &self,
        request: ExperimentalResourceListRequest,
    ) -> anyhow::Result<ExperimentalResourceListResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("experimental")
            .push("resource");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ExperimentalResourceListRequest::parse_response(response).await?)
    }
    /// List sessions
    ///
    /// Get a list of all OpenCode sessions across projects, sorted by most recently updated. Archived sessions are excluded by default.
    ///
    /// * Path: `GET /experimental/session`
    pub async fn experimental_session_list(
        &self,
        request: ExperimentalSessionListRequest,
    ) -> anyhow::Result<ExperimentalSessionListResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("experimental")
            .push("session");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ExperimentalSessionListRequest::parse_response(response).await?)
    }
    /// List tools
    ///
    /// Get a list of available tools with their JSON schema parameters for a specific provider and model combination.
    ///
    /// * Path: `GET /experimental/tool`
    pub async fn tool_list(&self, request: ToolListRequest) -> anyhow::Result<ToolListResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("experimental")
            .push("tool");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ToolListRequest::parse_response(response).await?)
    }
    /// List tool IDs
    ///
    /// Get a list of all available tool IDs, including both built-in tools and dynamically registered tools.
    ///
    /// * Path: `GET /experimental/tool/ids`
    pub async fn tool_ids(&self, request: ToolIdsRequest) -> anyhow::Result<ToolIdsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("experimental")
            .push("tool")
            .push("ids");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ToolIdsRequest::parse_response(response).await?)
    }
    /// List workspaces
    ///
    /// List all workspaces.
    ///
    /// * Path: `GET /experimental/workspace`
    pub async fn experimental_workspace_list(
        &self,
        request: ExperimentalWorkspaceListRequest,
    ) -> anyhow::Result<ExperimentalWorkspaceListResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("experimental")
            .push("workspace");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ExperimentalWorkspaceListRequest::parse_response(response).await?)
    }
    /// Create workspace
    ///
    /// Create a workspace for the current project.
    ///
    /// * Path: `POST /experimental/workspace`
    pub async fn experimental_workspace_create(
        &self,
        request: ExperimentalWorkspaceCreateRequest,
    ) -> anyhow::Result<ExperimentalWorkspaceCreateResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("experimental")
            .push("workspace");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(ExperimentalWorkspaceCreateRequest::parse_response(response).await?)
    }
    /// Remove workspace
    ///
    /// Remove an existing workspace.
    ///
    /// * Path: `DELETE /experimental/workspace/{id}`
    pub async fn experimental_workspace_remove(
        &self,
        request: ExperimentalWorkspaceRemoveRequest,
    ) -> anyhow::Result<ExperimentalWorkspaceCreateResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("experimental")
            .push("workspace")
            .push(&request.path.id.to_string());
        let response = self.client.delete(url).query(&request.query).send().await?;
        Ok(ExperimentalWorkspaceRemoveRequest::parse_response(response).await?)
    }
    /// List worktrees
    ///
    /// List all sandbox worktrees for the current project.
    ///
    /// * Path: `GET /experimental/worktree`
    pub async fn worktree_list(&self, request: WorktreeListRequest) -> anyhow::Result<FindFilesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("experimental")
            .push("worktree");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(WorktreeListRequest::parse_response(response).await?)
    }
    /// Create worktree
    ///
    /// Create a new git worktree for the current project and run any configured startup scripts.
    ///
    /// * Path: `POST /experimental/worktree`
    pub async fn worktree_create(&self, request: WorktreeCreateRequest) -> anyhow::Result<WorktreeCreateResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("experimental")
            .push("worktree");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(WorktreeCreateRequest::parse_response(response).await?)
    }
    /// Remove worktree
    ///
    /// Remove a git worktree and delete its branch.
    ///
    /// * Path: `DELETE /experimental/worktree`
    pub async fn worktree_remove(&self, request: WorktreeRemoveRequest) -> anyhow::Result<AppLogResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("experimental")
            .push("worktree");
        let mut req_builder = self.client.delete(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(WorktreeRemoveRequest::parse_response(response).await?)
    }
    /// Reset worktree
    ///
    /// Reset a worktree branch to the primary default branch.
    ///
    /// * Path: `POST /experimental/worktree/reset`
    pub async fn worktree_reset(&self, request: WorktreeResetRequest) -> anyhow::Result<AppLogResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("experimental")
            .push("worktree")
            .push("reset");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(WorktreeResetRequest::parse_response(response).await?)
    }
    /// List files
    ///
    /// List files and directories in a specified path.
    ///
    /// * Path: `GET /file`
    pub async fn file_list(&self, request: FileListRequest) -> anyhow::Result<FileListResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("file");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(FileListRequest::parse_response(response).await?)
    }
    /// Read file
    ///
    /// Read the content of a specified file.
    ///
    /// * Path: `GET /file/content`
    pub async fn file_read(&self, request: FileReadRequest) -> anyhow::Result<FileReadResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("file")
            .push("content");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(FileReadRequest::parse_response(response).await?)
    }
    /// Get file status
    ///
    /// Get the git status of all files in the project.
    ///
    /// * Path: `GET /file/status`
    pub async fn file_status(&self, request: FileStatusRequest) -> anyhow::Result<FileStatusResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("file")
            .push("status");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(FileStatusRequest::parse_response(response).await?)
    }
    /// Find text
    ///
    /// Search for text patterns across files in the project using ripgrep.
    ///
    /// * Path: `GET /find`
    pub async fn find_text(&self, request: FindTextRequest) -> anyhow::Result<FindTextResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("find");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(FindTextRequest::parse_response(response).await?)
    }
    /// Find files
    ///
    /// Search for files or directories by name or pattern in the project directory.
    ///
    /// * Path: `GET /find/file`
    pub async fn find_files(&self, request: FindFilesRequest) -> anyhow::Result<FindFilesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("find")
            .push("file");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(FindFilesRequest::parse_response(response).await?)
    }
    /// Find symbols
    ///
    /// Search for workspace symbols like functions, classes, and variables using LSP.
    ///
    /// * Path: `GET /find/symbol`
    pub async fn find_symbols(&self, request: FindSymbolsRequest) -> anyhow::Result<FindSymbolsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("find")
            .push("symbol");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(FindSymbolsRequest::parse_response(response).await?)
    }
    /// Get formatter status
    ///
    /// Get formatter status
    ///
    /// * Path: `GET /formatter`
    pub async fn formatter_status(&self, request: FormatterStatusRequest) -> anyhow::Result<FormatterStatusResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("formatter");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(FormatterStatusRequest::parse_response(response).await?)
    }
    /// Get global configuration
    ///
    /// Retrieve the current global OpenCode configuration settings and preferences.
    ///
    /// * Path: `GET /global/config`
    pub async fn global_config_get(&self, request: GlobalConfigGetRequest) -> anyhow::Result<ConfigGetResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("global")
            .push("config");
        let response = self.client.get(url).send().await?;
        Ok(GlobalConfigGetRequest::parse_response(response).await?)
    }
    /// Update global configuration
    ///
    /// Update global OpenCode configuration settings and preferences.
    ///
    /// * Path: `PATCH /global/config`
    pub async fn global_config_update(
        &self,
        request: GlobalConfigUpdateRequest,
    ) -> anyhow::Result<ConfigUpdateResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("global")
            .push("config");
        let mut req_builder = self.client.patch(url);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(GlobalConfigUpdateRequest::parse_response(response).await?)
    }
    /// Dispose instance
    ///
    /// Clean up and dispose all OpenCode instances, releasing all resources.
    ///
    /// * Path: `POST /global/dispose`
    pub async fn global_dispose(&self, request: GlobalDisposeRequest) -> anyhow::Result<McpConnectResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("global")
            .push("dispose");
        let response = self.client.post(url).send().await?;
        Ok(GlobalDisposeRequest::parse_response(response).await?)
    }
    /// Get global events
    ///
    /// Subscribe to global events from the OpenCode system using server-sent events.
    ///
    /// * Path: `GET /global/event`
    pub async fn global_event(&self, request: GlobalEventRequest) -> anyhow::Result<GlobalEventResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("global")
            .push("event");
        let response = self.client.get(url).send().await?;
        Ok(GlobalEventRequest::parse_response(response).await?)
    }
    /// Get health
    ///
    /// Get health information about the OpenCode server.
    ///
    /// * Path: `GET /global/health`
    pub async fn global_health(&self, request: GlobalHealthRequest) -> anyhow::Result<GlobalHealthResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("global")
            .push("health");
        let response = self.client.get(url).send().await?;
        Ok(GlobalHealthRequest::parse_response(response).await?)
    }
    /// Upgrade opencode
    ///
    /// Upgrade opencode to the specified version or latest if not specified.
    ///
    /// * Path: `POST /global/upgrade`
    pub async fn global_upgrade(&self, request: GlobalUpgradeRequest) -> anyhow::Result<GlobalUpgradeResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("global")
            .push("upgrade");
        let mut req_builder = self.client.post(url);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(GlobalUpgradeRequest::parse_response(response).await?)
    }
    /// Dispose instance
    ///
    /// Clean up and dispose the current OpenCode instance, releasing all resources.
    ///
    /// * Path: `POST /instance/dispose`
    pub async fn instance_dispose(&self, request: InstanceDisposeRequest) -> anyhow::Result<McpConnectResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("instance")
            .push("dispose");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(InstanceDisposeRequest::parse_response(response).await?)
    }
    /// Write log
    ///
    /// Write a log entry to the server logs with specified level and metadata.
    ///
    /// * Path: `POST /log`
    pub async fn app_log(&self, request: AppLogRequest) -> anyhow::Result<AppLogResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("log");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(AppLogRequest::parse_response(response).await?)
    }
    /// Get LSP status
    ///
    /// Get LSP server status
    ///
    /// * Path: `GET /lsp`
    pub async fn lsp_status(&self, request: LspStatusRequest) -> anyhow::Result<LspStatusResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("lsp");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(LspStatusRequest::parse_response(response).await?)
    }
    /// Get MCP status
    ///
    /// Get the status of all Model Context Protocol (MCP) servers.
    ///
    /// * Path: `GET /mcp`
    pub async fn mcp_status(&self, request: McpStatusRequest) -> anyhow::Result<McpStatusResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("mcp");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(McpStatusRequest::parse_response(response).await?)
    }
    /// Add MCP server
    ///
    /// Dynamically add a new Model Context Protocol (MCP) server to the system.
    ///
    /// * Path: `POST /mcp`
    pub async fn mcp_add(&self, request: McpAddRequest) -> anyhow::Result<McpAddResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("mcp");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(McpAddRequest::parse_response(response).await?)
    }
    /// Start MCP OAuth
    ///
    /// Start OAuth authentication flow for a Model Context Protocol (MCP) server.
    ///
    /// * Path: `POST /mcp/{name}/auth`
    pub async fn mcp_auth_start(&self, request: McpAuthStartRequest) -> anyhow::Result<McpAuthStartResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("mcp")
            .push(&request.path.name.to_string())
            .push("auth");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(McpAuthStartRequest::parse_response(response).await?)
    }
    /// Remove MCP OAuth
    ///
    /// Remove OAuth credentials for an MCP server
    ///
    /// * Path: `DELETE /mcp/{name}/auth`
    pub async fn mcp_auth_remove(&self, request: McpAuthRemoveRequest) -> anyhow::Result<McpAuthRemoveResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("mcp")
            .push(&request.path.name.to_string())
            .push("auth");
        let response = self.client.delete(url).query(&request.query).send().await?;
        Ok(McpAuthRemoveRequest::parse_response(response).await?)
    }
    /// Authenticate MCP OAuth
    ///
    /// Start OAuth flow and wait for callback (opens browser)
    ///
    /// * Path: `POST /mcp/{name}/auth/authenticate`
    pub async fn mcp_auth_authenticate(
        &self,
        request: McpAuthAuthenticateRequest,
    ) -> anyhow::Result<McpAuthCallbackResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("mcp")
            .push(&request.path.name.to_string())
            .push("auth")
            .push("authenticate");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(McpAuthAuthenticateRequest::parse_response(response).await?)
    }
    /// Complete MCP OAuth
    ///
    /// Complete OAuth authentication for a Model Context Protocol (MCP) server using the authorization code.
    ///
    /// * Path: `POST /mcp/{name}/auth/callback`
    pub async fn mcp_auth_callback(&self, request: McpAuthCallbackRequest) -> anyhow::Result<McpAuthCallbackResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("mcp")
            .push(&request.path.name.to_string())
            .push("auth")
            .push("callback");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(McpAuthCallbackRequest::parse_response(response).await?)
    }
    /// Connect an MCP server
    ///
    /// * Path: `POST /mcp/{name}/connect`
    pub async fn mcp_connect(&self, request: McpConnectRequest) -> anyhow::Result<McpConnectResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("mcp")
            .push(&request.path.name.to_string())
            .push("connect");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(McpConnectRequest::parse_response(response).await?)
    }
    /// Disconnect an MCP server
    ///
    /// * Path: `POST /mcp/{name}/disconnect`
    pub async fn mcp_disconnect(&self, request: McpDisconnectRequest) -> anyhow::Result<McpConnectResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("mcp")
            .push(&request.path.name.to_string())
            .push("disconnect");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(McpDisconnectRequest::parse_response(response).await?)
    }
    /// Get paths
    ///
    /// Retrieve the current working directory and related path information for the OpenCode instance.
    ///
    /// * Path: `GET /path`
    pub async fn path_get(&self, request: PathGetRequest) -> anyhow::Result<PathGetResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("path");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(PathGetRequest::parse_response(response).await?)
    }
    /// List pending permissions
    ///
    /// Get all pending permission requests across all sessions.
    ///
    /// * Path: `GET /permission`
    pub async fn permission_list(&self, request: PermissionListRequest) -> anyhow::Result<PermissionListResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("permission");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(PermissionListRequest::parse_response(response).await?)
    }
    /// Respond to permission request
    ///
    /// Approve or deny a permission request from the AI assistant.
    ///
    /// * Path: `POST /permission/{requestID}/reply`
    pub async fn permission_reply(&self, request: PermissionReplyRequest) -> anyhow::Result<PartDeleteResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("permission")
            .push(&request.path.request_id.to_string())
            .push("reply");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(PermissionReplyRequest::parse_response(response).await?)
    }
    /// List all projects
    ///
    /// Get a list of projects that have been opened with OpenCode.
    ///
    /// * Path: `GET /project`
    pub async fn project_list(&self, request: ProjectListRequest) -> anyhow::Result<ProjectListResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("project");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ProjectListRequest::parse_response(response).await?)
    }
    /// Get current project
    ///
    /// Retrieve the currently active project that OpenCode is working with.
    ///
    /// * Path: `GET /project/current`
    pub async fn project_current(&self, request: ProjectCurrentRequest) -> anyhow::Result<ProjectCurrentResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("project")
            .push("current");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ProjectCurrentRequest::parse_response(response).await?)
    }
    /// Initialize git repository
    ///
    /// Create a git repository for the current project and return the refreshed project info.
    ///
    /// * Path: `POST /project/git/init`
    pub async fn project_init_git(&self, request: ProjectInitGitRequest) -> anyhow::Result<ProjectCurrentResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("project")
            .push("git")
            .push("init");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(ProjectInitGitRequest::parse_response(response).await?)
    }
    /// Update project
    ///
    /// Update project properties such as name, icon, and commands.
    ///
    /// * Path: `PATCH /project/{projectID}`
    pub async fn project_update(&self, request: ProjectUpdateRequest) -> anyhow::Result<ProjectUpdateResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("project")
            .push(&request.path.project_id.to_string());
        let mut req_builder = self.client.patch(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(ProjectUpdateRequest::parse_response(response).await?)
    }
    /// List providers
    ///
    /// Get a list of all available AI providers, including both available and connected ones.
    ///
    /// * Path: `GET /provider`
    pub async fn provider_list(&self, request: ProviderListRequest) -> anyhow::Result<ProviderListResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("provider");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ProviderListRequest::parse_response(response).await?)
    }
    /// Get provider auth methods
    ///
    /// Retrieve available authentication methods for all AI providers.
    ///
    /// * Path: `GET /provider/auth`
    pub async fn provider_auth(&self, request: ProviderAuthRequest) -> anyhow::Result<ProviderAuthResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("provider")
            .push("auth");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ProviderAuthRequest::parse_response(response).await?)
    }
    /// OAuth authorize
    ///
    /// Initiate OAuth authorization for a specific AI provider to get an authorization URL.
    ///
    /// * Path: `POST /provider/{providerID}/oauth/authorize`
    pub async fn provider_oauth_authorize(
        &self,
        request: ProviderOauthAuthorizeRequest,
    ) -> anyhow::Result<ProviderOauthAuthorizeResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("provider")
            .push(&request.path.provider_id.to_string())
            .push("oauth")
            .push("authorize");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(ProviderOauthAuthorizeRequest::parse_response(response).await?)
    }
    /// OAuth callback
    ///
    /// Handle the OAuth callback from a provider after user authorization.
    ///
    /// * Path: `POST /provider/{providerID}/oauth/callback`
    pub async fn provider_oauth_callback(
        &self,
        request: ProviderOauthCallbackRequest,
    ) -> anyhow::Result<AppLogResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("provider")
            .push(&request.path.provider_id.to_string())
            .push("oauth")
            .push("callback");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(ProviderOauthCallbackRequest::parse_response(response).await?)
    }
    /// List PTY sessions
    ///
    /// Get a list of all active pseudo-terminal (PTY) sessions managed by OpenCode.
    ///
    /// * Path: `GET /pty`
    pub async fn pty_list(&self, request: PtyListRequest) -> anyhow::Result<PtyListResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("pty");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(PtyListRequest::parse_response(response).await?)
    }
    /// Create PTY session
    ///
    /// Create a new pseudo-terminal (PTY) session for running shell commands and processes.
    ///
    /// * Path: `POST /pty`
    pub async fn pty_create(&self, request: PtyCreateRequest) -> anyhow::Result<PtyCreateResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("pty");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(PtyCreateRequest::parse_response(response).await?)
    }
    /// Get PTY session
    ///
    /// Retrieve detailed information about a specific pseudo-terminal (PTY) session.
    ///
    /// * Path: `GET /pty/{ptyID}`
    pub async fn pty_get(&self, request: PtyGetRequest) -> anyhow::Result<PtyGetResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("pty")
            .push(&request.path.pty_id.to_string());
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(PtyGetRequest::parse_response(response).await?)
    }
    /// Update PTY session
    ///
    /// Update properties of an existing pseudo-terminal (PTY) session.
    ///
    /// * Path: `PUT /pty/{ptyID}`
    pub async fn pty_update(&self, request: PtyUpdateRequest) -> anyhow::Result<PtyCreateResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("pty")
            .push(&request.path.pty_id.to_string());
        let mut req_builder = self.client.put(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(PtyUpdateRequest::parse_response(response).await?)
    }
    /// Remove PTY session
    ///
    /// Remove and terminate a specific pseudo-terminal (PTY) session.
    ///
    /// * Path: `DELETE /pty/{ptyID}`
    pub async fn pty_remove(&self, request: PtyRemoveRequest) -> anyhow::Result<PtyRemoveResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("pty")
            .push(&request.path.pty_id.to_string());
        let response = self.client.delete(url).query(&request.query).send().await?;
        Ok(PtyRemoveRequest::parse_response(response).await?)
    }
    /// Connect to PTY session
    ///
    /// Establish a WebSocket connection to interact with a pseudo-terminal (PTY) session in real-time.
    ///
    /// * Path: `GET /pty/{ptyID}/connect`
    pub async fn pty_connect(&self, request: PtyConnectRequest) -> anyhow::Result<PtyRemoveResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("pty")
            .push(&request.path.pty_id.to_string())
            .push("connect");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(PtyConnectRequest::parse_response(response).await?)
    }
    /// List pending questions
    ///
    /// Get all pending question requests across all sessions.
    ///
    /// * Path: `GET /question`
    pub async fn question_list(&self, request: QuestionListRequest) -> anyhow::Result<QuestionListResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("question");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(QuestionListRequest::parse_response(response).await?)
    }
    /// Reject question request
    ///
    /// Reject a question request from the AI assistant.
    ///
    /// * Path: `POST /question/{requestID}/reject`
    pub async fn question_reject(&self, request: QuestionRejectRequest) -> anyhow::Result<PartDeleteResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("question")
            .push(&request.path.request_id.to_string())
            .push("reject");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(QuestionRejectRequest::parse_response(response).await?)
    }
    /// Reply to question request
    ///
    /// Provide answers to a question request from the AI assistant.
    ///
    /// * Path: `POST /question/{requestID}/reply`
    pub async fn question_reply(&self, request: QuestionReplyRequest) -> anyhow::Result<PartDeleteResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("question")
            .push(&request.path.request_id.to_string())
            .push("reply");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(QuestionReplyRequest::parse_response(response).await?)
    }
    /// List sessions
    ///
    /// Get a list of all OpenCode sessions, sorted by most recently updated.
    ///
    /// * Path: `GET /session`
    pub async fn session_list(&self, request: SessionListRequest) -> anyhow::Result<SessionListResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(SessionListRequest::parse_response(response).await?)
    }
    /// Create session
    ///
    /// Create a new OpenCode session for interacting with AI assistants and managing conversations.
    ///
    /// * Path: `POST /session`
    pub async fn session_create(&self, request: SessionCreateRequest) -> anyhow::Result<SessionCreateResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(SessionCreateRequest::parse_response(response).await?)
    }
    /// Get session status
    ///
    /// Retrieve the current status of all sessions, including active, idle, and completed states.
    ///
    /// * Path: `GET /session/status`
    pub async fn session_status(&self, request: SessionStatusRequest) -> anyhow::Result<SessionStatusResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push("status");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(SessionStatusRequest::parse_response(response).await?)
    }
    /// Get session
    ///
    /// Retrieve detailed information about a specific OpenCode session.
    ///
    /// * Path: `GET /session/{sessionID}`
    pub async fn session_get(&self, request: SessionGetRequest) -> anyhow::Result<SessionGetResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string());
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(SessionGetRequest::parse_response(response).await?)
    }
    /// Delete session
    ///
    /// Delete a session and permanently remove all associated data, including messages and history.
    ///
    /// * Path: `DELETE /session/{sessionID}`
    pub async fn session_delete(&self, request: SessionDeleteRequest) -> anyhow::Result<PartDeleteResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string());
        let response = self.client.delete(url).query(&request.query).send().await?;
        Ok(SessionDeleteRequest::parse_response(response).await?)
    }
    /// Update session
    ///
    /// Update properties of an existing session, such as title or other metadata.
    ///
    /// * Path: `PATCH /session/{sessionID}`
    pub async fn session_update(&self, request: SessionUpdateRequest) -> anyhow::Result<SessionGetResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string());
        let mut req_builder = self.client.patch(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(SessionUpdateRequest::parse_response(response).await?)
    }
    /// Abort session
    ///
    /// Abort an active session and stop any ongoing AI processing or command execution.
    ///
    /// * Path: `POST /session/{sessionID}/abort`
    pub async fn session_abort(&self, request: SessionAbortRequest) -> anyhow::Result<PartDeleteResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("abort");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(SessionAbortRequest::parse_response(response).await?)
    }
    /// Get session children
    ///
    /// Retrieve all child sessions that were forked from the specified parent session.
    ///
    /// * Path: `GET /session/{sessionID}/children`
    pub async fn session_children(&self, request: SessionChildrenRequest) -> anyhow::Result<SessionChildrenResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("children");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(SessionChildrenRequest::parse_response(response).await?)
    }
    /// Send command
    ///
    /// Send a new command to a session for execution by the AI assistant.
    ///
    /// * Path: `POST /session/{sessionID}/command`
    pub async fn session_command(&self, request: SessionCommandRequest) -> anyhow::Result<SessionPromptResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("command");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(SessionCommandRequest::parse_response(response).await?)
    }
    /// Get message diff
    ///
    /// Get the file changes (diff) that resulted from a specific user message in the session.
    ///
    /// * Path: `GET /session/{sessionID}/diff`
    pub async fn session_diff(&self, request: SessionDiffRequest) -> anyhow::Result<SessionDiffResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("diff");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(SessionDiffRequest::parse_response(response).await?)
    }
    /// Fork session
    ///
    /// Create a new session by forking an existing session at a specific message point.
    ///
    /// * Path: `POST /session/{sessionID}/fork`
    pub async fn session_fork(&self, request: SessionForkRequest) -> anyhow::Result<SessionForkResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("fork");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(SessionForkRequest::parse_response(response).await?)
    }
    /// Initialize session
    ///
    /// Analyze the current application and create an AGENTS.md file with project-specific agent configurations.
    ///
    /// * Path: `POST /session/{sessionID}/init`
    pub async fn session_init(&self, request: SessionInitRequest) -> anyhow::Result<PartDeleteResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("init");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(SessionInitRequest::parse_response(response).await?)
    }
    /// Get session messages
    ///
    /// Retrieve all messages in a session, including user prompts and AI responses.
    ///
    /// * Path: `GET /session/{sessionID}/message`
    pub async fn session_messages(&self, request: SessionMessagesRequest) -> anyhow::Result<SessionMessagesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("message");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(SessionMessagesRequest::parse_response(response).await?)
    }
    /// Send message
    ///
    /// Create and send a new message to a session, streaming the AI response.
    ///
    /// * Path: `POST /session/{sessionID}/message`
    pub async fn session_prompt(&self, request: SessionPromptRequest) -> anyhow::Result<SessionPromptResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("message");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(SessionPromptRequest::parse_response(response).await?)
    }
    /// Get message
    ///
    /// Retrieve a specific message from a session by its message ID.
    ///
    /// * Path: `GET /session/{sessionID}/message/{messageID}`
    pub async fn session_message(&self, request: SessionMessageRequest) -> anyhow::Result<SessionMessageResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("message")
            .push(&request.path.message_id.to_string());
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(SessionMessageRequest::parse_response(response).await?)
    }
    /// Delete message
    ///
    /// Permanently delete a specific message (and all of its parts) from a session. This does not revert any file changes that may have been made while processing the message.
    ///
    /// * Path: `DELETE /session/{sessionID}/message/{messageID}`
    pub async fn session_delete_message(
        &self,
        request: SessionDeleteMessageRequest,
    ) -> anyhow::Result<PartDeleteResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("message")
            .push(&request.path.message_id.to_string());
        let response = self.client.delete(url).query(&request.query).send().await?;
        Ok(SessionDeleteMessageRequest::parse_response(response).await?)
    }
    /// Delete a part from a message
    ///
    /// * Path: `DELETE /session/{sessionID}/message/{messageID}/part/{partID}`
    pub async fn part_delete(&self, request: PartDeleteRequest) -> anyhow::Result<PartDeleteResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("message")
            .push(&request.path.message_id.to_string())
            .push("part")
            .push(&request.path.part_id.to_string());
        let response = self.client.delete(url).query(&request.query).send().await?;
        Ok(PartDeleteRequest::parse_response(response).await?)
    }
    /// Update a part in a message
    ///
    /// * Path: `PATCH /session/{sessionID}/message/{messageID}/part/{partID}`
    pub async fn part_update(&self, request: PartUpdateRequest) -> anyhow::Result<PartUpdateResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("message")
            .push(&request.path.message_id.to_string())
            .push("part")
            .push(&request.path.part_id.to_string());
        let mut req_builder = self.client.patch(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(PartUpdateRequest::parse_response(response).await?)
    }
    /// Respond to permission
    ///
    /// Approve or deny a permission request from the AI assistant.
    ///
    /// * Path: `POST /session/{sessionID}/permissions/{permissionID}`
    pub async fn permission_respond(&self, request: PermissionRespondRequest) -> anyhow::Result<PartDeleteResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("permissions")
            .push(&request.path.permission_id.to_string());
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(PermissionRespondRequest::parse_response(response).await?)
    }
    /// Send async message
    ///
    /// Create and send a new message to a session asynchronously, starting the session if needed and returning immediately.
    ///
    /// * Path: `POST /session/{sessionID}/prompt_async`
    pub async fn session_prompt_async(
        &self,
        request: SessionPromptAsyncRequest,
    ) -> anyhow::Result<SessionPromptAsyncResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("prompt_async");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(SessionPromptAsyncRequest::parse_response(response).await?)
    }
    /// Revert message
    ///
    /// Revert a specific message in a session, undoing its effects and restoring the previous state.
    ///
    /// * Path: `POST /session/{sessionID}/revert`
    pub async fn session_revert(&self, request: SessionRevertRequest) -> anyhow::Result<SessionGetResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("revert");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(SessionRevertRequest::parse_response(response).await?)
    }
    /// Share session
    ///
    /// Create a shareable link for a session, allowing others to view the conversation.
    ///
    /// * Path: `POST /session/{sessionID}/share`
    pub async fn session_share(&self, request: SessionShareRequest) -> anyhow::Result<SessionGetResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("share");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(SessionShareRequest::parse_response(response).await?)
    }
    /// Unshare session
    ///
    /// Remove the shareable link for a session, making it private again.
    ///
    /// * Path: `DELETE /session/{sessionID}/share`
    pub async fn session_unshare(&self, request: SessionUnshareRequest) -> anyhow::Result<SessionGetResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("share");
        let response = self.client.delete(url).query(&request.query).send().await?;
        Ok(SessionUnshareRequest::parse_response(response).await?)
    }
    /// Run shell command
    ///
    /// Execute a shell command within the session context and return the AI's response.
    ///
    /// * Path: `POST /session/{sessionID}/shell`
    pub async fn session_shell(&self, request: SessionShellRequest) -> anyhow::Result<SessionShellResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("shell");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(SessionShellRequest::parse_response(response).await?)
    }
    /// Summarize session
    ///
    /// Generate a concise summary of the session using AI compaction to preserve key information.
    ///
    /// * Path: `POST /session/{sessionID}/summarize`
    pub async fn session_summarize(&self, request: SessionSummarizeRequest) -> anyhow::Result<PartDeleteResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("summarize");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(SessionSummarizeRequest::parse_response(response).await?)
    }
    /// Get session todos
    ///
    /// Retrieve the todo list associated with a specific session, showing tasks and action items.
    ///
    /// * Path: `GET /session/{sessionID}/todo`
    pub async fn session_todo(&self, request: SessionTodoRequest) -> anyhow::Result<SessionTodoResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("todo");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(SessionTodoRequest::parse_response(response).await?)
    }
    /// Restore reverted messages
    ///
    /// Restore all previously reverted messages in a session.
    ///
    /// * Path: `POST /session/{sessionID}/unrevert`
    pub async fn session_unrevert(&self, request: SessionUnrevertRequest) -> anyhow::Result<SessionGetResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("session")
            .push(&request.path.session_id.to_string())
            .push("unrevert");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(SessionUnrevertRequest::parse_response(response).await?)
    }
    /// List skills
    ///
    /// Get a list of all available skills in the OpenCode system.
    ///
    /// * Path: `GET /skill`
    pub async fn app_skills(&self, request: AppSkillsRequest) -> anyhow::Result<FindTextResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("skill");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(AppSkillsRequest::parse_response(response).await?)
    }
    /// Append TUI prompt
    ///
    /// Append prompt to the TUI
    ///
    /// * Path: `POST /tui/append-prompt`
    pub async fn tui_append_prompt(&self, request: TuiAppendPromptRequest) -> anyhow::Result<AppLogResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("tui")
            .push("append-prompt");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(TuiAppendPromptRequest::parse_response(response).await?)
    }
    /// Clear TUI prompt
    ///
    /// Clear the prompt
    ///
    /// * Path: `POST /tui/clear-prompt`
    pub async fn tui_clear_prompt(&self, request: TuiClearPromptRequest) -> anyhow::Result<McpConnectResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("tui")
            .push("clear-prompt");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(TuiClearPromptRequest::parse_response(response).await?)
    }
    /// Get next TUI request
    ///
    /// Retrieve the next TUI (Terminal User Interface) request from the queue for processing.
    ///
    /// * Path: `GET /tui/control/next`
    pub async fn tui_control_next(&self, request: TuiControlNextRequest) -> anyhow::Result<TuiControlNextResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("tui")
            .push("control")
            .push("next");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(TuiControlNextRequest::parse_response(response).await?)
    }
    /// Submit TUI response
    ///
    /// Submit a response to the TUI request queue to complete a pending request.
    ///
    /// * Path: `POST /tui/control/response`
    pub async fn tui_control_response(&self, request: TuiControlResponseRequest) -> anyhow::Result<McpConnectResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("tui")
            .push("control")
            .push("response");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(TuiControlResponseRequest::parse_response(response).await?)
    }
    /// Execute TUI command
    ///
    /// Execute a TUI command (e.g. agent_cycle)
    ///
    /// * Path: `POST /tui/execute-command`
    pub async fn tui_execute_command(&self, request: TuiExecuteCommandRequest) -> anyhow::Result<AppLogResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("tui")
            .push("execute-command");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(TuiExecuteCommandRequest::parse_response(response).await?)
    }
    /// Open help dialog
    ///
    /// Open the help dialog in the TUI to display user assistance information.
    ///
    /// * Path: `POST /tui/open-help`
    pub async fn tui_open_help(&self, request: TuiOpenHelpRequest) -> anyhow::Result<McpConnectResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("tui")
            .push("open-help");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(TuiOpenHelpRequest::parse_response(response).await?)
    }
    /// Open models dialog
    ///
    /// Open the model dialog
    ///
    /// * Path: `POST /tui/open-models`
    pub async fn tui_open_models(&self, request: TuiOpenModelsRequest) -> anyhow::Result<McpConnectResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("tui")
            .push("open-models");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(TuiOpenModelsRequest::parse_response(response).await?)
    }
    /// Open sessions dialog
    ///
    /// Open the session dialog
    ///
    /// * Path: `POST /tui/open-sessions`
    pub async fn tui_open_sessions(&self, request: TuiOpenSessionsRequest) -> anyhow::Result<McpConnectResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("tui")
            .push("open-sessions");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(TuiOpenSessionsRequest::parse_response(response).await?)
    }
    /// Open themes dialog
    ///
    /// Open the theme dialog
    ///
    /// * Path: `POST /tui/open-themes`
    pub async fn tui_open_themes(&self, request: TuiOpenThemesRequest) -> anyhow::Result<McpConnectResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("tui")
            .push("open-themes");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(TuiOpenThemesRequest::parse_response(response).await?)
    }
    /// Publish TUI event
    ///
    /// Publish a TUI event
    ///
    /// * Path: `POST /tui/publish`
    pub async fn tui_publish(&self, request: TuiPublishRequest) -> anyhow::Result<AppLogResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("tui")
            .push("publish");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(TuiPublishRequest::parse_response(response).await?)
    }
    /// Select session
    ///
    /// Navigate the TUI to display the specified session.
    ///
    /// * Path: `POST /tui/select-session`
    pub async fn tui_select_session(&self, request: TuiSelectSessionRequest) -> anyhow::Result<PartDeleteResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("tui")
            .push("select-session");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(TuiSelectSessionRequest::parse_response(response).await?)
    }
    /// Show TUI toast
    ///
    /// Show a toast notification in the TUI
    ///
    /// * Path: `POST /tui/show-toast`
    pub async fn tui_show_toast(&self, request: TuiShowToastRequest) -> anyhow::Result<McpConnectResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("tui")
            .push("show-toast");
        let mut req_builder = self.client.post(url).query(&request.query);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(TuiShowToastRequest::parse_response(response).await?)
    }
    /// Submit TUI prompt
    ///
    /// Submit the prompt
    ///
    /// * Path: `POST /tui/submit-prompt`
    pub async fn tui_submit_prompt(&self, request: TuiSubmitPromptRequest) -> anyhow::Result<McpConnectResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("tui")
            .push("submit-prompt");
        let response = self.client.post(url).query(&request.query).send().await?;
        Ok(TuiSubmitPromptRequest::parse_response(response).await?)
    }
    /// Get VCS info
    ///
    /// Retrieve version control system (VCS) information for the current project, such as git branch.
    ///
    /// * Path: `GET /vcs`
    pub async fn vcs_get(&self, request: VcsGetRequest) -> anyhow::Result<VcsGetResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("vcs");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(VcsGetRequest::parse_response(response).await?)
    }
}
